name: Maven Build and Goals Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Validate Maven Project
        run: mvn validate

      - name: Compile the Project
        run: mvn compile

      - name: Run Tests
        run: mvn test

      - name: Package the Application
        run: mvn package

      - name: Verify the Build
        run: mvn verify

      - name: Install Artifacts Locally
        run: mvn install

      - name: Generate Site Documentation
        run: mvn site

      - name: Deploy the Application
        run: mvn deploy -DaltDeploymentRepository=my-repo::default::file://$HOME/.m2/repository

      - name: Clean the Project
        run: mvn clean
